# Generated by Django 5.1.3 on 2024-11-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vottings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.ImageField(upload_to='static/candidate/'),
        ),
    ]
