# Generated by Django 5.1.3 on 2024-11-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vottings', '0002_alter_candidate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.ImageField(upload_to='svottings/tatic/candidate/'),
        ),
    ]
