# Generated by Django 5.1.3 on 2024-11-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vottings', '0004_alter_candidate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.ImageField(upload_to='e_voting_system/static/candidate/'),
        ),
    ]
